// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTAXuH4h29WALb_6gKiSCBB34R2NGm9KI',
    appId: '1:402277201733:web:dc6a4d20834a5e5229702c',
    messagingSenderId: '402277201733',
    projectId: 'allowance-fa781',
    authDomain: 'allowance-fa781.firebaseapp.com',
    storageBucket: 'allowance-fa781.appspot.com',
    measurementId: 'G-PLG4JJN224',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTxNib5A0YZgPl0JKlgFWc8ZNEWGep3lI',
    appId: '1:402277201733:android:5397375b84bf290029702c',
    messagingSenderId: '402277201733',
    projectId: 'allowance-fa781',
    storageBucket: 'allowance-fa781.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn-u0IS7xc86YFTcsj1Jx0d4Wq7aM-mS0',
    appId: '1:402277201733:ios:dca18110f282d33029702c',
    messagingSenderId: '402277201733',
    projectId: 'allowance-fa781',
    storageBucket: 'allowance-fa781.appspot.com',
    iosClientId: '402277201733-th8d9nr5noosv96a0frodclg6p2l8g9g.apps.googleusercontent.com',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDn-u0IS7xc86YFTcsj1Jx0d4Wq7aM-mS0',
    appId: '1:402277201733:ios:dca18110f282d33029702c',
    messagingSenderId: '402277201733',
    projectId: 'allowance-fa781',
    storageBucket: 'allowance-fa781.appspot.com',
    iosClientId: '402277201733-th8d9nr5noosv96a0frodclg6p2l8g9g.apps.googleusercontent.com',
    iosBundleId: 'com.example.test',
  );
}
