// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWSaTXomHiw49SmHC1DAwolLu2msr0ayk',
    appId: '1:109373102144:web:a115e7f4be851c725ea7a5',
    messagingSenderId: '109373102144',
    projectId: 'allowance-38891',
    authDomain: 'allowance-38891.firebaseapp.com',
    storageBucket: 'allowance-38891.appspot.com',
    measurementId: 'G-L0PBRH96FH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOuib78vRsbeCHaDaZAkeuTv8mZD_X1yw',
    appId: '1:109373102144:android:a4d85ec8df37b9bf5ea7a5',
    messagingSenderId: '109373102144',
    projectId: 'allowance-38891',
    storageBucket: 'allowance-38891.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD68kA_S5ELSVdaTLqO5ozFEMUrkqStwMY',
    appId: '1:109373102144:ios:8065729ee1aa88455ea7a5',
    messagingSenderId: '109373102144',
    projectId: 'allowance-38891',
    storageBucket: 'allowance-38891.appspot.com',
    iosClientId: '109373102144-tcr53durclg0su3fljtaachumqib7e2i.apps.googleusercontent.com',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD68kA_S5ELSVdaTLqO5ozFEMUrkqStwMY',
    appId: '1:109373102144:ios:8065729ee1aa88455ea7a5',
    messagingSenderId: '109373102144',
    projectId: 'allowance-38891',
    storageBucket: 'allowance-38891.appspot.com',
    iosClientId: '109373102144-tcr53durclg0su3fljtaachumqib7e2i.apps.googleusercontent.com',
    iosBundleId: 'com.example.test',
  );
}
