platform :ios, '11.0'

target 'Runner' do
  use_frameworks!

     pod 'Firebase/Core', '~> 8.0'
     pod 'Firebase/Auth', '~> 8.0'
     pod 'Firebase/Firestore', '~> 8.0'
     pod 'GoogleFontsiOS/Outfit'
     pod 'GoogleFontsiOS/Inter'
end
